name: Go Mod Tidy Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      # Step 3: Verify Go Mod Tidy
      - name: Verify go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
        working-directory: ./ # Adjust if your `go.mod` is in a subdirectory
